void main() {
  // print("hi");
  // var num = 10 ~/ 0;
  // print(num);
  // print("thank U");

  // print("Hi");
  // try {
  //   var num = 10 ~/ 0;
  //   print(num);
  // } on UnsupportedError {
  //   print("Exception occured");
  // }
  // print("Thank you");

  // print("hi");
  // try {
  //   var num = 10 ~/ 0;
  //   print("num");
  // } catch (e) {
  //   print("Exceotion occured $e");
  // }
